apiVersion: v1
kind: Namespace
metadata:
  name: kafka-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: eventhub-kafka-producer-secrets
  namespace: kafka-demo
type: Opaque
stringData:
  KAFKA_SASL_JAAS_CONFIG: ''
  AZURE_STORAGE_CONNECTION_STRING: ''
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-kafka-producer
  namespace: kafka-demo
  labels:
    app: eventhub-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhub-kafka-producer
  template:
    metadata:
      labels:
        app: eventhub-kafka-producer
    spec:
      containers:
        - name: eventhub-kafka-producer
          image: mydemoreg.azurecr.io/eventhub-kafka-producer:4
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: eventhub-kafka-producer-secrets
                  key: KAFKA_SASL_JAAS_CONFIG
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: eventhub-kafka-producer-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "8Gi"
              cpu: "1500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eventhub-kafka-producer
  namespace: kafka-demo
spec:
  selector:
    app: eventhub-kafka-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---

