apiVersion: v1
kind: Namespace
metadata:
  name: kafka-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-kafka-producer
  namespace: kafka-demo
  labels:
    app: eventhub-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhub-kafka-producer
  template:
    metadata:
      labels:
        app: eventhub-kafka-producer
    spec:
      containers:
        - name: eventhub-kafka-producer
          image: mydemoreg.azurecr.io/eventhub-kafka-producer:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eventhub-kafka-producer
  namespace: kafka-demo
spec:
  selector:
    app: eventhub-kafka-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
